/**
 * Generates platform-specific Headlamp product metadata, resolves packaged resources, and records
 * external-tool digests for post-build verification.
 */
const { createHash } = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');

const { resolveHeadlampPaths, resolveWithin } = require('./paths.ts');
const { createProductTemplate: createTemplate, projectManifest } = require(
  './product-manifest.ts'
);

/**
 * Calculates the SHA-256 digest of a file.
 *
 * @param file - File whose contents are hashed.
 * @returns The lowercase hexadecimal digest.
 */
function sha256(file: string): string {
  const hash = createHash('sha256');
  hash.update(fs.readFileSync(file));
  return hash.digest('hex');
}

/**
 * Maps the host platform to a supported product-manifest platform.
 *
 * @returns The supported platform name, or `undefined` on another platform.
 */
function platformName(): 'darwin' | 'linux' | 'win32' | undefined {
  if (
    process.platform === 'darwin' ||
    process.platform === 'linux' ||
    process.platform === 'win32'
  ) {
    return process.platform;
  }
  return undefined;
}

/**
 * Creates a portable path relative to the generated manifest.
 *
 * @param file - Absolute file path to make relative.
 * @param manifestPath - Absolute generated manifest path.
 * @returns A slash-delimited relative path.
 */
function relativeFromManifest(file: string, manifestPath: string): string {
  return path
    .relative(path.dirname(manifestPath), file)
    .split(path.sep)
    .join('/');
}

/**
 * Appends generated common resources without replacing product-defined groups.
 *
 * @param existingResources - Optional resource groups copied from product configuration.
 * @param generatedCommon - Common resources generated by the consumer package.
 * @returns Merged common and platform-specific resource groups.
 */
function mergeProductResources(existingResources: unknown, generatedCommon: any[]) {
  if (
    existingResources !== undefined &&
    (typeof existingResources !== 'object' ||
      existingResources === null ||
      Array.isArray(existingResources))
  ) {
    throw new Error('headlamp.resources must be an object');
  }
  const resources = (existingResources || {}) as Record<string, unknown>;
  if (resources.common !== undefined && !Array.isArray(resources.common)) {
    throw new Error('headlamp.resources.common must be an array');
  }
  return {
    ...resources,
    common: [...((resources.common as any[]) || []), ...generatedCommon],
  };
}

/**
 * Creates a verified external-tool record for one platform.
 *
 * @param id - Stable tool identifier.
 * @param platform - Runtime platform key.
 * @param file - Tool file whose digest is recorded.
 * @param packagedPath - Tool path in the packaged application.
 * @param verificationPath - Packaged file path verified after assembly.
 * @returns The manifest tool record plus assembly-only path metadata.
 */
function toolRecord(
  id: string,
  platform: string,
  file: string,
  packagedPath: string,
  verificationPath: string
) {
  if (!fs.existsSync(file) || !fs.statSync(file).isFile()) {
    throw new Error(`Required bundled tool is missing: ${file}`);
  }
  return {
    id,
    platforms: {
      [platform]: {
        path: packagedPath,
        sha256: sha256(file),
      },
    },
    packagedPath,
    verificationPath,
  };
}

/**
 * Creates product metadata without consumer-only build fields.
 *
 * @param rootDir - Consumer project root.
 * @returns The product manifest template.
 */
function createProductTemplate(rootDir = path.resolve(process.env.INIT_CWD || process.cwd())) {
  const project = projectManifest(rootDir);
  return createTemplate(project);
}

/**
 * Creates a platform-specific product manifest and resolves its destination.
 *
 * @param options - Optional root, package, and platform overrides.
 * @returns The generated manifest object and absolute destination path.
 */
function createManifest(options: any = {}) {
  const rootDir = path.resolve(options.rootDir || process.env.INIT_CWD || process.cwd());
  const packageDir = path.resolve(options.packageDir || path.join(__dirname, '..', '..'));
  const project = projectManifest(rootDir);
  const build = project.headlamp?.build;
  if (!build || !Array.isArray(build.resources) || !Array.isArray(build.externalTools)) {
    throw new Error(
      'package.json must declare headlamp.build resources and externalTools'
    );
  }
  const { appDir, manifestPath } = resolveHeadlampPaths(packageDir, build.manifest);
  const template = createTemplate(project);
  const platform = options.platform || platformName();
  if (!platform) {
    throw new Error(`Unsupported build platform: ${process.platform}`);
  }

  const tools = build.externalTools.map((tool: any) => {
    const platformTool = tool.platforms?.[platform];
    if (!platformTool) {
      throw new Error(`External tool ${tool.id} has no ${platform} configuration`);
    }
    return toolRecord(
      tool.id,
      platform,
      resolveWithin(appDir, platformTool.file, `External tool ${tool.id}`),
      platformTool.path,
      platformTool.verificationPath || platformTool.path
    );
  });

  template['external-tools'] = tools.map(
    ({ packagedPath, verificationPath, ...tool }) => tool
  );
  template.resources = mergeProductResources(
    template.resources,
    build.resources.map((resource: any) => {
      if (resource.base !== 'headlampApp' && resource.base !== 'project') {
        throw new Error(
          `Product resource base must be "headlampApp" or "project": ${resource.base}`
        );
      }
      return {
        from: relativeFromManifest(
          resolveWithin(
            resource.base === 'headlampApp' ? appDir : rootDir,
            resource.from,
            'Product resource'
          ),
          manifestPath
        ),
        to: resource.to,
      };
    })
  );
  template.verify = tools.map(tool => ({
    path: tool.verificationPath,
    sha256: tool.platforms[platform].sha256,
    platforms: [
      platform === 'darwin' ? 'mac' : platform === 'win32' ? 'win' : platform,
    ],
  }));
  return { manifest: template, manifestPath };
}

/**
 * Serializes the product manifest expected on disk.
 *
 * @param options - Optional root, package, and platform overrides.
 * @returns Serialized manifest content and its absolute destination path.
 */
function expectedManifest(options?: any): { content: string; manifestPath: string } {
  const { manifest, manifestPath } = createManifest(options);
  return { content: `${JSON.stringify(manifest, null, 2)}\n`, manifestPath };
}

/**
 * Generates the configured product manifest on disk.
 *
 * @param options - Optional root, package, and platform overrides.
 * @returns Nothing.
 */
function generateManifest(options?: any): void {
  const { content, manifestPath } = expectedManifest(options);
  fs.mkdirSync(path.dirname(manifestPath), { recursive: true });
  fs.writeFileSync(manifestPath, content);
  console.log(`Generated ${manifestPath}`);
}

/**
 * Verifies that the generated product manifest is present and current.
 *
 * @param options - Optional root, package, and platform overrides.
 * @returns Nothing.
 */
function verifyManifest(options?: any): void {
  const { content, manifestPath } = expectedManifest(options);
  if (
    !fs.existsSync(manifestPath) ||
    fs.readFileSync(manifestPath, 'utf8') !== content
  ) {
    throw new Error(
      'Generated product manifest is missing or stale; run manifest:generate'
    );
  }
  console.log('Headlamp source package and product manifest are consistent.');
}

module.exports = {
  createManifest,
  createProductTemplate,
  generateManifest,
  mergeProductResources,
  verifyManifest,
};
