/**
 * Synthetic test fixtures for edge-case coverage.
 *
 * These deliberately target languages and formats NOT represented in the real
 * fixtures found in testFixtures.ts (Go, Node/Express, Helm YAML, C#/.NET,
 * Terraform HCL).
 */

/** Helper: simulate a Rich code panel line with ANSI color codes. */
function panelLine(content: string, keyColor = '97;40'): string {
  const padded = content.padEnd(78);
  return `\x1b[40m \x1b[0m\x1b[${keyColor}m${padded}\x1b[0m\x1b[40m \x1b[0m`;
}

/** Helper: blank panel line (just [40m background filling the whole width) */
function panelBlank(): string {
  return '\x1b[40m' + ' '.repeat(80) + '\x1b[0m';
}

// ---------------------------------------------------------------------------
// 1. Go HTTP server — `:=`, `defer`, `go func`, `import (...)` block
// ---------------------------------------------------------------------------

export const syntheticGoHttpServer = [
  'stty -echo',
  '\x1b[?2004l',
  '\x1b[?2004hroot@aks-agent-abc123:/app# ',
  '\x1b[?2004l',
  '',
  "Loaded models: ['azure/gpt-4']",
  '✅ Toolset core_investigation',
  '\x1b[1;96mAI:\x1b[0m ',
  'Here is a minimal Go HTTP server deployed to Kubernetes.',
  '',
  '                           \x1b[1mmain.go\x1b[0m                                   ',
  '',
  panelBlank(),
  panelLine('package main'),
  panelLine(''),
  panelLine('import ('),
  panelLine('  "fmt"'),
  panelLine('  "log"'),
  panelLine('  "net/http"'),
  panelLine('  "os"'),
  panelLine(')'),
  panelLine(''),
  panelLine('func healthz(w http.ResponseWriter, r *http.Request) {'),
  panelLine('  w.WriteHeader(http.StatusOK)'),
  panelLine('  fmt.Fprintln(w, "ok")'),
  panelLine('}'),
  panelLine(''),
  panelLine('func main() {'),
  panelLine('  port := os.Getenv("PORT")'),
  panelLine('  if port == "" {'),
  panelLine('    port = "8080"'),
  panelLine('  }'),
  panelLine(''),
  panelLine('  mux := http.NewServeMux()'),
  panelLine('  mux.HandleFunc("/healthz", healthz)'),
  panelLine('  mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {'),
  panelLine('    fmt.Fprintln(w, "hello from go")'),
  panelLine('  })'),
  panelLine(''),
  panelLine('  srv := &http.Server{Addr: ":" + port, Handler: mux}'),
  panelLine('  go func() {'),
  panelLine('    log.Println("shutting down...")'),
  panelLine('  }()'),
  panelLine(''),
  panelLine('  log.Printf("listening on :%s\\n", port)'),
  panelLine('  if err := srv.ListenAndServe(); err != nil {'),
  panelLine('    log.Fatal(err)'),
  panelLine('  }'),
  panelLine('}'),
  panelBlank(),
  '',
  '                          \x1b[1mDockerfile\x1b[0m                                ',
  '',
  panelBlank(),
  panelLine('FROM golang:1.22-alpine AS builder'),
  panelLine('WORKDIR /app'),
  panelLine('COPY go.mod go.sum ./'),
  panelLine('RUN go mod download'),
  panelLine('COPY . .'),
  panelLine('RUN CGO_ENABLED=0 go build -o server .'),
  panelLine(''),
  panelLine('FROM gcr.io/distroless/static:nonroot'),
  panelLine('COPY --from=builder /app/server /server'),
  panelLine('EXPOSE 8080'),
  panelLine('ENTRYPOINT ["/server"]'),
  panelBlank(),
  '',
  'Build and deploy:',
  '',
  panelBlank(),
  panelLine('docker build -t myregistry/go-app:1.0 .'),
  panelLine('kubectl apply -f k8s.yaml'),
  panelBlank(),
  '',
  '\x1b[?2004hroot@aks-agent-abc123:/app# ',
].join('\n');

// ---------------------------------------------------------------------------
// 2. Node.js Express — `require()`, arrow functions, `async/await`
// ---------------------------------------------------------------------------

export const syntheticNodeExpressApp = [
  'stty -echo',
  '\x1b[?2004l',
  '\x1b[?2004hroot@aks-agent-def456:/app# ',
  '\x1b[?2004l',
  '',
  "Loaded models: ['azure/gpt-4']",
  '✅ Toolset core_investigation',
  '\x1b[1;96mAI:\x1b[0m ',
  'Here is a simple Express.js server:',
  '',
  '                        \x1b[1mpackage.json\x1b[0m                              ',
  '',
  panelBlank(),
  panelLine('{'),
  panelLine('  "name": "express-k8s-demo",'),
  panelLine('  "version": "1.0.0",'),
  panelLine('  "main": "index.js",'),
  panelLine('  "scripts": {'),
  panelLine('    "start": "node index.js"'),
  panelLine('  },'),
  panelLine('  "dependencies": {'),
  panelLine('    "express": "^4.18.2"'),
  panelLine('  }'),
  panelLine('}'),
  panelBlank(),
  '',
  '                         \x1b[1mindex.js\x1b[0m                                  ',
  '',
  panelBlank(),
  panelLine("const express = require('express');"),
  panelLine('const app = express();'),
  panelLine(''),
  panelLine('app.get("/healthz", (req, res) => {'),
  panelLine('  res.status(200).send("ok");'),
  panelLine('});'),
  panelLine(''),
  panelLine('app.get("/", async (req, res) => {'),
  panelLine('  const message = process.env.GREETING || "hello from node";'),
  panelLine('  res.json({ message });'),
  panelLine('});'),
  panelLine(''),
  panelLine('const PORT = process.env.PORT || 3000;'),
  panelLine('app.listen(PORT, () => {'),
  panelLine('  console.log(`Server running on port ${PORT}`);'),
  panelLine('});'),
  panelBlank(),
  '',
  '                         \x1b[1mDockerfile\x1b[0m                                ',
  '',
  panelBlank(),
  panelLine('FROM node:20-alpine'),
  panelLine('WORKDIR /app'),
  panelLine('COPY package*.json ./'),
  panelLine('RUN npm ci --production'),
  panelLine('COPY . .'),
  panelLine('EXPOSE 3000'),
  panelLine('USER node'),
  panelLine('CMD ["node", "index.js"]'),
  panelBlank(),
  '',
  '\x1b[?2004hroot@aks-agent-def456:/app# ',
].join('\n');

// ---------------------------------------------------------------------------
// 3. Helm values.yaml — anchors, nested maps, non-K8s YAML
// ---------------------------------------------------------------------------

export const syntheticHelmValuesYaml = [
  'stty -echo',
  '\x1b[?2004l',
  '\x1b[?2004hroot@aks-agent-ghi789:/app# ',
  '\x1b[?2004l',
  '',
  "Loaded models: ['azure/gpt-4']",
  '\x1b[1;96mAI:\x1b[0m ',
  'Here is a Helm values.yaml for your nginx-ingress deployment:',
  '',
  '## Custom values.yaml',
  '',
  'controller:',
  '  name: controller',
  '  replicaCount: 2',
  '  resources:',
  '    requests:',
  '      cpu: 100m',
  '      memory: 128Mi',
  '    limits:',
  '      cpu: 500m',
  '      memory: 512Mi',
  '  config:',
  '    proxy-body-size: "50m"',
  '    use-forwarded-headers: "true"',
  '  service:',
  '    type: LoadBalancer',
  '    annotations:',
  '      service.beta.kubernetes.io/azure-load-balancer-internal: "true"',
  '  metrics:',
  '    enabled: true',
  '    serviceMonitor:',
  '      enabled: true',
  '      namespace: monitoring',
  'defaultBackend:',
  '  enabled: true',
  '  replicaCount: 1',
  '',
  'Install with:',
  '',
  'helm install ingress-nginx ingress-nginx/ingress-nginx -f values.yaml -n ingress-system --create-namespace',
  '',
  '\x1b[?2004hroot@aks-agent-ghi789:/app# ',
].join('\n');

// ---------------------------------------------------------------------------
// 4. C# / .NET — `using`, `namespace`, `var`, `async Task`
// ---------------------------------------------------------------------------

export const syntheticCSharpDotnetApp = [
  'stty -echo',
  '\x1b[?2004l',
  '\x1b[?2004hroot@aks-agent-jkl012:/app# ',
  '\x1b[?2004l',
  '',
  "Loaded models: ['azure/gpt-4']",
  '✅ Toolset core_investigation',
  '\x1b[1;96mAI:\x1b[0m ',
  'Here is a minimal ASP.NET Core web API:',
  '',
  '                        \x1b[1mProgram.cs\x1b[0m                                ',
  '',
  panelBlank(),
  panelLine('using Microsoft.AspNetCore.Builder;'),
  panelLine('using Microsoft.Extensions.Hosting;'),
  panelLine(''),
  panelLine('var builder = WebApplication.CreateBuilder(args);'),
  panelLine('var app = builder.Build();'),
  panelLine(''),
  panelLine('app.MapGet("/", () => "hello from dotnet");'),
  panelLine('app.MapGet("/healthz", () => Results.Ok("healthy"));'),
  panelLine(''),
  panelLine('app.Run();'),
  panelBlank(),
  '',
  '                         \x1b[1mDockerfile\x1b[0m                                ',
  '',
  panelBlank(),
  panelLine('FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build'),
  panelLine('WORKDIR /src'),
  panelLine('COPY *.csproj .'),
  panelLine('RUN dotnet restore'),
  panelLine('COPY . .'),
  panelLine('RUN dotnet publish -c Release -o /app'),
  panelLine(''),
  panelLine('FROM mcr.microsoft.com/dotnet/aspnet:8.0'),
  panelLine('WORKDIR /app'),
  panelLine('COPY --from=build /app .'),
  panelLine('EXPOSE 8080'),
  panelLine('ENTRYPOINT ["dotnet", "MyApi.dll"]'),
  panelBlank(),
  '',
  'Build and run:',
  '',
  panelBlank(),
  panelLine('dotnet publish -c Release'),
  panelLine('docker build -t myregistry/dotnet-api:1.0 .'),
  panelLine('kubectl apply -f k8s.yaml'),
  panelBlank(),
  '',
  '\x1b[?2004hroot@aks-agent-jkl012:/app# ',
].join('\n');

// ---------------------------------------------------------------------------
// 5. Terraform HCL — `resource`, `variable`, `output`, provider blocks
// ---------------------------------------------------------------------------

export const syntheticTerraformAksModule = [
  'stty -echo',
  '\x1b[?2004l',
  '\x1b[?2004hroot@aks-agent-mno345:/app# ',
  '\x1b[?2004l',
  '',
  "Loaded models: ['azure/gpt-4']",
  '\x1b[1;96mAI:\x1b[0m ',
  'Here is a Terraform module to create an AKS cluster:',
  '',
  '### providers.tf',
  '',
  '```hcl',
  'terraform {',
  '  required_providers {',
  '    azurerm = {',
  '      source  = "hashicorp/azurerm"',
  '      version = "~> 3.80"',
  '    }',
  '  }',
  '}',
  '',
  'provider "azurerm" {',
  '  features {}',
  '}',
  '```',
  '',
  '### variables.tf',
  '',
  '```hcl',
  'variable "cluster_name" {',
  '  type    = string',
  '  default = "my-aks"',
  '}',
  '',
  'variable "node_count" {',
  '  type    = number',
  '  default = 2',
  '}',
  '',
  'variable "vm_size" {',
  '  type    = string',
  '  default = "Standard_B2s"',
  '}',
  '```',
  '',
  '### main.tf',
  '',
  '```hcl',
  'resource "azurerm_resource_group" "aks" {',
  '  name     = "${var.cluster_name}-rg"',
  '  location = "eastus"',
  '}',
  '',
  'resource "azurerm_kubernetes_cluster" "aks" {',
  '  name                = var.cluster_name',
  '  location            = azurerm_resource_group.aks.location',
  '  resource_group_name = azurerm_resource_group.aks.name',
  '  dns_prefix          = var.cluster_name',
  '',
  '  default_node_pool {',
  '    name       = "default"',
  '    node_count = var.node_count',
  '    vm_size    = var.vm_size',
  '  }',
  '',
  '  identity {',
  '    type = "SystemAssigned"',
  '  }',
  '}',
  '```',
  '',
  'Apply with:',
  '',
  '```bash',
  'terraform init',
  'terraform plan -out=tfplan',
  'terraform apply tfplan',
  '```',
  '',
  '\x1b[?2004hroot@aks-agent-mno345:/app# ',
].join('\n');

// ---------------------------------------------------------------------------
// 6. Ruby Sinatra app — class, def, end, require, do…end blocks
// ---------------------------------------------------------------------------

export const syntheticRubyRailsApp = [
  'stty -echo',
  '\x1b[?2004l',
  '\x1b[?2004hroot@aks-agent-rby001:/app# ',
  '\x1b[?2004l',
  '',
  "Loaded models: ['azure/gpt-4']",
  '\x1b[1;96mAI:\x1b[0m ',
  'Here is a minimal Sinatra web app:',
  '',
  '                           \x1b[1mapp.rb\x1b[0m                                    ',
  '',
  panelBlank(),
  panelLine("require 'sinatra'"),
  panelLine("require 'json'"),
  panelLine(''),
  panelLine('class App < Sinatra::Base'),
  panelLine("  get '/healthz' do"),
  panelLine('    status 200'),
  panelLine("    'ok'"),
  panelLine('  end'),
  panelLine(''),
  panelLine("  get '/' do"),
  panelLine('    content_type :json'),
  panelLine("    { message: 'hello from ruby' }.to_json"),
  panelLine('  end'),
  panelLine('end'),
  panelBlank(),
  '',
  '                          \x1b[1mGemfile\x1b[0m                                   ',
  '',
  panelBlank(),
  panelLine("source 'https://rubygems.org'"),
  panelLine("gem 'sinatra'"),
  panelLine("gem 'puma'"),
  panelBlank(),
  '',
  '                         \x1b[1mDockerfile\x1b[0m                                ',
  '',
  panelBlank(),
  panelLine('FROM ruby:3.3-slim'),
  panelLine('WORKDIR /app'),
  panelLine('COPY Gemfile* ./'),
  panelLine('RUN bundle install'),
  panelLine('COPY . .'),
  panelLine('EXPOSE 4567'),
  panelLine('CMD ["ruby", "app.rb", "-o", "0.0.0.0"]'),
  panelBlank(),
  '',
  '\x1b[?2004hroot@aks-agent-rby001:/app# ',
].join('\n');

// ---------------------------------------------------------------------------
// 7. Python with triple-quotes, f-strings, raw strings
// ---------------------------------------------------------------------------

export const syntheticPythonMultilineStrings = [
  'stty -echo',
  '\x1b[?2004l',
  '\x1b[?2004hroot@aks-agent-py002:/app# ',
  '\x1b[?2004l',
  '',
  "Loaded models: ['azure/gpt-4']",
  '\x1b[1;96mAI:\x1b[0m ',
  'Here is a Python config with multiline strings:',
  '',
  '                         \x1b[1mconfig.py\x1b[0m                                 ',
  '',
  panelBlank(),
  panelLine('"""Application configuration module."""'),
  panelLine(''),
  panelLine('import os'),
  panelLine('from pathlib import Path'),
  panelLine(''),
  panelLine('BASE_DIR = Path(__file__).parent'),
  panelLine(''),
  panelLine('HELP_TEXT = """'),
  panelLine('Usage: python app.py [OPTIONS]'),
  panelLine(''),
  panelLine('Options:'),
  panelLine('  --port PORT    Port to listen on'),
  panelLine('  --debug        Enable debug mode'),
  panelLine('"""'),
  panelLine(''),
  panelLine('def get_db_url():'),
  panelLine('    host = os.environ.get("DB_HOST", "localhost")'),
  panelLine('    return f"postgresql://{host}:5432/mydb"'),
  panelBlank(),
  '',
  '\x1b[?2004hroot@aks-agent-py002:/app# ',
].join('\n');

// ---------------------------------------------------------------------------
// 8. Bash script with here-document <<EOF…EOF
// ---------------------------------------------------------------------------

export const syntheticBashHeredoc = [
  'stty -echo',
  '\x1b[?2004l',
  '\x1b[?2004hroot@aks-agent-bash01:/app# ',
  '\x1b[?2004l',
  '',
  "Loaded models: ['azure/gpt-4']",
  '\x1b[1;96mAI:\x1b[0m ',
  'Here is a setup script that creates a config file:',
  '',
  '                         \x1b[1msetup.sh\x1b[0m                                  ',
  '',
  panelBlank(),
  panelLine('#!/bin/bash'),
  panelLine('set -euo pipefail'),
  panelLine(''),
  panelLine('NAMESPACE="${1:-default}"'),
  panelLine(''),
  panelLine('cat <<EOF | kubectl apply -f -'),
  panelLine('apiVersion: v1'),
  panelLine('kind: ConfigMap'),
  panelLine('metadata:'),
  panelLine('  name: app-config'),
  panelLine('  namespace: $NAMESPACE'),
  panelLine('data:'),
  panelLine('  APP_ENV: "production"'),
  panelLine('  LOG_LEVEL: "info"'),
  panelLine('EOF'),
  panelLine(''),
  panelLine('echo "ConfigMap created in namespace $NAMESPACE"'),
  panelBlank(),
  '',
  'Run it:',
  '',
  panelBlank(),
  panelLine('chmod +x setup.sh'),
  panelLine('./setup.sh my-namespace'),
  panelBlank(),
  '',
  '\x1b[?2004hroot@aks-agent-bash01:/app# ',
].join('\n');

// ---------------------------------------------------------------------------
// 9. Numbered steps with code between them
// ---------------------------------------------------------------------------

export const syntheticNumberedStepsWithCode = [
  'stty -echo',
  '\x1b[?2004l',
  '\x1b[?2004hroot@aks-agent-step01:/app# ',
  '\x1b[?2004l',
  '',
  "Loaded models: ['azure/gpt-4']",
  '\x1b[1;96mAI:\x1b[0m ',
  'Follow these steps to set up monitoring:',
  '',
  '\x1b[1m1) Create the namespace\x1b[0m',
  '',
  panelBlank(),
  panelLine('kubectl create namespace monitoring'),
  panelBlank(),
  '',
  '\x1b[1m2) Install Prometheus\x1b[0m',
  '',
  panelBlank(),
  panelLine('helm repo add prometheus-community https://prometheus-community.github.io/helm-charts'),
  panelLine('helm install prometheus prometheus-community/prometheus -n monitoring'),
  panelBlank(),
  '',
  '\x1b[1m3) Verify it is running\x1b[0m',
  '',
  panelBlank(),
  panelLine('kubectl get pods -n monitoring'),
  panelLine('kubectl port-forward -n monitoring svc/prometheus-server 9090:80'),
  panelBlank(),
  '',
  'Then open http://localhost:9090 in your browser.',
  '',
  '\x1b[?2004hroot@aks-agent-step01:/app# ',
].join('\n');

// ---------------------------------------------------------------------------
// 10. Makefile with targets, .PHONY, shell commands
// ---------------------------------------------------------------------------

export const syntheticMakefileWithTargets = [
  'stty -echo',
  '\x1b[?2004l',
  '\x1b[?2004hroot@aks-agent-make01:/app# ',
  '\x1b[?2004l',
  '',
  "Loaded models: ['azure/gpt-4']",
  '\x1b[1;96mAI:\x1b[0m ',
  'Here is a Makefile for building and deploying:',
  '',
  '                         \x1b[1mMakefile\x1b[0m                                  ',
  '',
  panelBlank(),
  panelLine('.PHONY: build test deploy clean'),
  panelLine(''),
  panelLine('IMAGE := myregistry/myapp'),
  panelLine('TAG   := $(shell git rev-parse --short HEAD)'),
  panelLine(''),
  panelLine('build:'),
  panelLine('\tdocker build -t $(IMAGE):$(TAG) .'),
  panelLine(''),
  panelLine('test:'),
  panelLine('\tgo test ./...'),
  panelLine(''),
  panelLine('deploy: build'),
  panelLine('\tkubectl set image deployment/myapp app=$(IMAGE):$(TAG)'),
  panelLine(''),
  panelLine('clean:'),
  panelLine('\tdocker rmi $(IMAGE):$(TAG) || true'),
  panelBlank(),
  '',
  '\x1b[?2004hroot@aks-agent-make01:/app# ',
].join('\n');

// ---------------------------------------------------------------------------
// 11. Mixed markdown-fenced code AND bare terminal-formatted code
// ---------------------------------------------------------------------------

export const syntheticMixedFencedAndBare = [
  'stty -echo',
  '\x1b[?2004l',
  '\x1b[?2004hroot@aks-agent-mix01:/app# ',
  '\x1b[?2004l',
  '',
  "Loaded models: ['azure/gpt-4']",
  '\x1b[1;96mAI:\x1b[0m ',
  'First, create the secret:',
  '',
  '```bash',
  'kubectl create secret generic db-creds \\',
  '  --from-literal=username=admin \\',
  '  --from-literal=password=s3cret',
  '```',
  '',
  'Then apply this deployment:',
  '',
  panelBlank(),
  panelLine('apiVersion: apps/v1'),
  panelLine('kind: Deployment'),
  panelLine('metadata:'),
  panelLine('  name: web-app'),
  panelLine('spec:'),
  panelLine('  replicas: 1'),
  panelLine('  selector:'),
  panelLine('    matchLabels:'),
  panelLine('      app: web-app'),
  panelBlank(),
  '',
  'Verify with:',
  '',
  'kubectl get pods -l app=web-app',
  '',
  '\x1b[?2004hroot@aks-agent-mix01:/app# ',
].join('\n');

// ---------------------------------------------------------------------------
// 12. YAML with anchors (&), aliases (*), merge keys (<<:)
// ---------------------------------------------------------------------------

export const syntheticYamlWithAnchors = [
  'stty -echo',
  '\x1b[?2004l',
  '\x1b[?2004hroot@aks-agent-anch01:/app# ',
  '\x1b[?2004l',
  '',
  "Loaded models: ['azure/gpt-4']",
  '\x1b[1;96mAI:\x1b[0m ',
  'Here is a K8s manifest using YAML anchors to avoid repetition:',
  '',
  '```yaml',
  'x-defaults: &defaults',
  '  resources:',
  '    requests:',
  '      cpu: 100m',
  '      memory: 128Mi',
  '    limits:',
  '      cpu: 500m',
  '      memory: 256Mi',
  '  securityContext:',
  '    runAsNonRoot: true',
  '    readOnlyRootFilesystem: true',
  '---',
  'apiVersion: apps/v1',
  'kind: Deployment',
  'metadata:',
  '  name: frontend',
  'spec:',
  '  template:',
  '    spec:',
  '      containers:',
  '        - name: app',
  '          <<: *defaults',
  '          image: frontend:1.0',
  '---',
  'apiVersion: apps/v1',
  'kind: Deployment',
  'metadata:',
  '  name: backend',
  'spec:',
  '  template:',
  '    spec:',
  '      containers:',
  '        - name: app',
  '          <<: *defaults',
  '          image: backend:2.0',
  '```',
  '',
  'Apply: `kubectl apply -f k8s.yaml`',
  '',
  '\x1b[?2004hroot@aks-agent-anch01:/app# ',
].join('\n');

// ---------------------------------------------------------------------------
// 13. 256-color and RGB ANSI codes
// ---------------------------------------------------------------------------

export const syntheticAnsi256ColorOutput = [
  'stty -echo',
  '\x1b[?2004l',
  '\x1b[?2004hroot@aks-agent-col01:/app# ',
  '\x1b[?2004l',
  '',
  "Loaded models: ['azure/gpt-4']",
  '\x1b[1;96mAI:\x1b[0m ',
  'Here is the deployment status:',
  '',
  '\x1b[38;5;82m✓\x1b[0m \x1b[38;5;255mdeployment/web-app\x1b[0m \x1b[38;5;245m2/2 ready\x1b[0m',
  '\x1b[38;5;82m✓\x1b[0m \x1b[38;5;255mservice/web-app\x1b[0m \x1b[38;5;245mClusterIP 10.0.0.5\x1b[0m',
  '\x1b[38;2;255;100;100m✗\x1b[0m \x1b[38;5;255mpod/web-app-abc123\x1b[0m \x1b[38;2;255;100;100mCrashLoopBackOff\x1b[0m',
  '',
  'The pod is crash-looping. Check logs:',
  '',
  'kubectl logs pod/web-app-abc123 --tail=50',
  '',
  '\x1b[?2004hroot@aks-agent-col01:/app# ',
].join('\n');

// ---------------------------------------------------------------------------
// 14. Deeply nested YAML (10+ levels)
// ---------------------------------------------------------------------------

export const syntheticDeepNestedYaml = [
  'stty -echo',
  '\x1b[?2004l',
  '\x1b[?2004hroot@aks-agent-deep01:/app# ',
  '\x1b[?2004l',
  '',
  "Loaded models: ['azure/gpt-4']",
  '\x1b[1;96mAI:\x1b[0m ',
  'Here is the Deployment with deep nesting:',
  '',
  panelBlank(),
  panelLine('apiVersion: apps/v1'),
  panelLine('kind: Deployment'),
  panelLine('metadata:'),
  panelLine('  name: nested-app'),
  panelLine('spec:'),
  panelLine('  template:'),
  panelLine('    spec:'),
  panelLine('      containers:'),
  panelLine('        - name: app'),
  panelLine('          volumeMounts:'),
  panelLine('            - name: config'),
  panelLine('              mountPath: /etc/config'),
  panelLine('              subPath: application.yaml'),
  panelLine('          env:'),
  panelLine('            - name: SPRING_CONFIG_LOCATION'),
  panelLine('              value: /etc/config/'),
  panelLine('          livenessProbe:'),
  panelLine('            httpGet:'),
  panelLine('              path: /actuator/health/liveness'),
  panelLine('              port: 8080'),
  panelLine('            initialDelaySeconds: 30'),
  panelBlank(),
  '',
  '\x1b[?2004hroot@aks-agent-deep01:/app# ',
].join('\n');

// ---------------------------------------------------------------------------
// 15. Multi-language comparison — Python, Go, Rust
// ---------------------------------------------------------------------------

export const syntheticMultiLanguageComparison = [
  'stty -echo',
  '\x1b[?2004l',
  '\x1b[?2004hroot@aks-agent-cmp01:/app# ',
  '\x1b[?2004l',
  '',
  "Loaded models: ['azure/gpt-4']",
  '\x1b[1;96mAI:\x1b[0m ',
  'Here is "Hello World" HTTP server in three languages:',
  '',
  '\x1b[1mPython (Flask):\x1b[0m',
  '',
  '```python',
  'from flask import Flask',
  'app = Flask(__name__)',
  '',
  '@app.route("/")',
  'def hello():',
  '    return "hello"',
  '```',
  '',
  '\x1b[1mGo:\x1b[0m',
  '',
  '```go',
  'package main',
  '',
  'import (',
  '    "fmt"',
  '    "net/http"',
  ')',
  '',
  'func main() {',
  '    http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {',
  '        fmt.Fprintln(w, "hello")',
  '    })',
  '    http.ListenAndServe(":8080", nil)',
  '}',
  '```',
  '',
  '\x1b[1mRust (Axum):\x1b[0m',
  '',
  '```rust',
  'use axum::{Router, routing::get};',
  '',
  'async fn hello() -> &\'static str { "hello" }',
  '',
  '#[tokio::main]',
  'async fn main() {',
  '    let app = Router::new().route("/", get(hello));',
  '    let listener = tokio::net::TcpListener::bind("0.0.0.0:8080").await.unwrap();',
  '    axum::serve(listener, app).await.unwrap();',
  '}',
  '```',
  '',
  'All three listen on port 8080.',
  '',
  '\x1b[?2004hroot@aks-agent-cmp01:/app# ',
].join('\n');
