/**
 * Synthetic test fixtures for edge-case coverage.
 *
 * These deliberately target languages and formats NOT represented in the real
 * fixtures found in testFixtures.ts (Go, Node/Express, Helm YAML, C#/.NET,
 * Terraform HCL).
 */

/** Helper: simulate a Rich code panel line with ANSI color codes. */
function panelLine(content: string, keyColor = '97;40'): string {
  const padded = content.padEnd(78);
  return `\x1b[40m \x1b[0m\x1b[${keyColor}m${padded}\x1b[0m\x1b[40m \x1b[0m`;
}

/** Helper: blank panel line (just [40m background filling the whole width) */
function panelBlank(): string {
  return '\x1b[40m' + ' '.repeat(80) + '\x1b[0m';
}

// ---------------------------------------------------------------------------
// 1. Go HTTP server — `:=`, `defer`, `go func`, `import (...)` block
// ---------------------------------------------------------------------------

export const syntheticGoHttpServer = [
  'stty -echo',
  '\x1b[?2004l',
  '\x1b[?2004hroot@aks-agent-abc123:/app# ',
  '\x1b[?2004l',
  '',
  "Loaded models: ['azure/gpt-4']",
  '✅ Toolset core_investigation',
  '\x1b[1;96mAI:\x1b[0m ',
  'Here is a minimal Go HTTP server deployed to Kubernetes.',
  '',
  '                           \x1b[1mmain.go\x1b[0m                                   ',
  '',
  panelBlank(),
  panelLine('package main'),
  panelLine(''),
  panelLine('import ('),
  panelLine('  "fmt"'),
  panelLine('  "log"'),
  panelLine('  "net/http"'),
  panelLine('  "os"'),
  panelLine(')'),
  panelLine(''),
  panelLine('func healthz(w http.ResponseWriter, r *http.Request) {'),
  panelLine('  w.WriteHeader(http.StatusOK)'),
  panelLine('  fmt.Fprintln(w, "ok")'),
  panelLine('}'),
  panelLine(''),
  panelLine('func main() {'),
  panelLine('  port := os.Getenv("PORT")'),
  panelLine('  if port == "" {'),
  panelLine('    port = "8080"'),
  panelLine('  }'),
  panelLine(''),
  panelLine('  mux := http.NewServeMux()'),
  panelLine('  mux.HandleFunc("/healthz", healthz)'),
  panelLine('  mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {'),
  panelLine('    fmt.Fprintln(w, "hello from go")'),
  panelLine('  })'),
  panelLine(''),
  panelLine('  srv := &http.Server{Addr: ":" + port, Handler: mux}'),
  panelLine('  go func() {'),
  panelLine('    log.Println("shutting down...")'),
  panelLine('  }()'),
  panelLine(''),
  panelLine('  log.Printf("listening on :%s\\n", port)'),
  panelLine('  if err := srv.ListenAndServe(); err != nil {'),
  panelLine('    log.Fatal(err)'),
  panelLine('  }'),
  panelLine('}'),
  panelBlank(),
  '',
  '                          \x1b[1mDockerfile\x1b[0m                                ',
  '',
  panelBlank(),
  panelLine('FROM golang:1.22-alpine AS builder'),
  panelLine('WORKDIR /app'),
  panelLine('COPY go.mod go.sum ./'),
  panelLine('RUN go mod download'),
  panelLine('COPY . .'),
  panelLine('RUN CGO_ENABLED=0 go build -o server .'),
  panelLine(''),
  panelLine('FROM gcr.io/distroless/static:nonroot'),
  panelLine('COPY --from=builder /app/server /server'),
  panelLine('EXPOSE 8080'),
  panelLine('ENTRYPOINT ["/server"]'),
  panelBlank(),
  '',
  'Build and deploy:',
  '',
  panelBlank(),
  panelLine('docker build -t myregistry/go-app:1.0 .'),
  panelLine('kubectl apply -f k8s.yaml'),
  panelBlank(),
  '',
  '\x1b[?2004hroot@aks-agent-abc123:/app# ',
].join('\n');

// ---------------------------------------------------------------------------
// 2. Node.js Express — `require()`, arrow functions, `async/await`
// ---------------------------------------------------------------------------

export const syntheticNodeExpressApp = [
  'stty -echo',
  '\x1b[?2004l',
  '\x1b[?2004hroot@aks-agent-def456:/app# ',
  '\x1b[?2004l',
  '',
  "Loaded models: ['azure/gpt-4']",
  '✅ Toolset core_investigation',
  '\x1b[1;96mAI:\x1b[0m ',
  'Here is a simple Express.js server:',
  '',
  '                        \x1b[1mpackage.json\x1b[0m                              ',
  '',
  panelBlank(),
  panelLine('{'),
  panelLine('  "name": "express-k8s-demo",'),
  panelLine('  "version": "1.0.0",'),
  panelLine('  "main": "index.js",'),
  panelLine('  "scripts": {'),
  panelLine('    "start": "node index.js"'),
  panelLine('  },'),
  panelLine('  "dependencies": {'),
  panelLine('    "express": "^4.18.2"'),
  panelLine('  }'),
  panelLine('}'),
  panelBlank(),
  '',
  '                         \x1b[1mindex.js\x1b[0m                                  ',
  '',
  panelBlank(),
  panelLine("const express = require('express');"),
  panelLine('const app = express();'),
  panelLine(''),
  panelLine('app.get("/healthz", (req, res) => {'),
  panelLine('  res.status(200).send("ok");'),
  panelLine('});'),
  panelLine(''),
  panelLine('app.get("/", async (req, res) => {'),
  panelLine('  const message = process.env.GREETING || "hello from node";'),
  panelLine('  res.json({ message });'),
  panelLine('});'),
  panelLine(''),
  panelLine('const PORT = process.env.PORT || 3000;'),
  panelLine('app.listen(PORT, () => {'),
  panelLine('  console.log(`Server running on port ${PORT}`);'),
  panelLine('});'),
  panelBlank(),
  '',
  '                         \x1b[1mDockerfile\x1b[0m                                ',
  '',
  panelBlank(),
  panelLine('FROM node:20-alpine'),
  panelLine('WORKDIR /app'),
  panelLine('COPY package*.json ./'),
  panelLine('RUN npm ci --production'),
  panelLine('COPY . .'),
  panelLine('EXPOSE 3000'),
  panelLine('USER node'),
  panelLine('CMD ["node", "index.js"]'),
  panelBlank(),
  '',
  '\x1b[?2004hroot@aks-agent-def456:/app# ',
].join('\n');

// ---------------------------------------------------------------------------
// 3. Helm values.yaml — anchors, nested maps, non-K8s YAML
// ---------------------------------------------------------------------------

export const syntheticHelmValuesYaml = [
  'stty -echo',
  '\x1b[?2004l',
  '\x1b[?2004hroot@aks-agent-ghi789:/app# ',
  '\x1b[?2004l',
  '',
  "Loaded models: ['azure/gpt-4']",
  '\x1b[1;96mAI:\x1b[0m ',
  'Here is a Helm values.yaml for your nginx-ingress deployment:',
  '',
  '## Custom values.yaml',
  '',
  'controller:',
  '  name: controller',
  '  replicaCount: 2',
  '  resources:',
  '    requests:',
  '      cpu: 100m',
  '      memory: 128Mi',
  '    limits:',
  '      cpu: 500m',
  '      memory: 512Mi',
  '  config:',
  '    proxy-body-size: "50m"',
  '    use-forwarded-headers: "true"',
  '  service:',
  '    type: LoadBalancer',
  '    annotations:',
  '      service.beta.kubernetes.io/azure-load-balancer-internal: "true"',
  '  metrics:',
  '    enabled: true',
  '    serviceMonitor:',
  '      enabled: true',
  '      namespace: monitoring',
  'defaultBackend:',
  '  enabled: true',
  '  replicaCount: 1',
  '',
  'Install with:',
  '',
  'helm install ingress-nginx ingress-nginx/ingress-nginx -f values.yaml -n ingress-system --create-namespace',
  '',
  '\x1b[?2004hroot@aks-agent-ghi789:/app# ',
].join('\n');

// ---------------------------------------------------------------------------
// 4. C# / .NET — `using`, `namespace`, `var`, `async Task`
// ---------------------------------------------------------------------------

export const syntheticCSharpDotnetApp = [
  'stty -echo',
  '\x1b[?2004l',
  '\x1b[?2004hroot@aks-agent-jkl012:/app# ',
  '\x1b[?2004l',
  '',
  "Loaded models: ['azure/gpt-4']",
  '✅ Toolset core_investigation',
  '\x1b[1;96mAI:\x1b[0m ',
  'Here is a minimal ASP.NET Core web API:',
  '',
  '                        \x1b[1mProgram.cs\x1b[0m                                ',
  '',
  panelBlank(),
  panelLine('using Microsoft.AspNetCore.Builder;'),
  panelLine('using Microsoft.Extensions.Hosting;'),
  panelLine(''),
  panelLine('var builder = WebApplication.CreateBuilder(args);'),
  panelLine('var app = builder.Build();'),
  panelLine(''),
  panelLine('app.MapGet("/", () => "hello from dotnet");'),
  panelLine('app.MapGet("/healthz", () => Results.Ok("healthy"));'),
  panelLine(''),
  panelLine('app.Run();'),
  panelBlank(),
  '',
  '                         \x1b[1mDockerfile\x1b[0m                                ',
  '',
  panelBlank(),
  panelLine('FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build'),
  panelLine('WORKDIR /src'),
  panelLine('COPY *.csproj .'),
  panelLine('RUN dotnet restore'),
  panelLine('COPY . .'),
  panelLine('RUN dotnet publish -c Release -o /app'),
  panelLine(''),
  panelLine('FROM mcr.microsoft.com/dotnet/aspnet:8.0'),
  panelLine('WORKDIR /app'),
  panelLine('COPY --from=build /app .'),
  panelLine('EXPOSE 8080'),
  panelLine('ENTRYPOINT ["dotnet", "MyApi.dll"]'),
  panelBlank(),
  '',
  'Build and run:',
  '',
  panelBlank(),
  panelLine('dotnet publish -c Release'),
  panelLine('docker build -t myregistry/dotnet-api:1.0 .'),
  panelLine('kubectl apply -f k8s.yaml'),
  panelBlank(),
  '',
  '\x1b[?2004hroot@aks-agent-jkl012:/app# ',
].join('\n');

// ---------------------------------------------------------------------------
// 5. Terraform HCL — `resource`, `variable`, `output`, provider blocks
// ---------------------------------------------------------------------------

export const syntheticTerraformAksModule = [
  'stty -echo',
  '\x1b[?2004l',
  '\x1b[?2004hroot@aks-agent-mno345:/app# ',
  '\x1b[?2004l',
  '',
  "Loaded models: ['azure/gpt-4']",
  '\x1b[1;96mAI:\x1b[0m ',
  'Here is a Terraform module to create an AKS cluster:',
  '',
  '### providers.tf',
  '',
  '```hcl',
  'terraform {',
  '  required_providers {',
  '    azurerm = {',
  '      source  = "hashicorp/azurerm"',
  '      version = "~> 3.80"',
  '    }',
  '  }',
  '}',
  '',
  'provider "azurerm" {',
  '  features {}',
  '}',
  '```',
  '',
  '### variables.tf',
  '',
  '```hcl',
  'variable "cluster_name" {',
  '  type    = string',
  '  default = "my-aks"',
  '}',
  '',
  'variable "node_count" {',
  '  type    = number',
  '  default = 2',
  '}',
  '',
  'variable "vm_size" {',
  '  type    = string',
  '  default = "Standard_B2s"',
  '}',
  '```',
  '',
  '### main.tf',
  '',
  '```hcl',
  'resource "azurerm_resource_group" "aks" {',
  '  name     = "${var.cluster_name}-rg"',
  '  location = "eastus"',
  '}',
  '',
  'resource "azurerm_kubernetes_cluster" "aks" {',
  '  name                = var.cluster_name',
  '  location            = azurerm_resource_group.aks.location',
  '  resource_group_name = azurerm_resource_group.aks.name',
  '  dns_prefix          = var.cluster_name',
  '',
  '  default_node_pool {',
  '    name       = "default"',
  '    node_count = var.node_count',
  '    vm_size    = var.vm_size',
  '  }',
  '',
  '  identity {',
  '    type = "SystemAssigned"',
  '  }',
  '}',
  '```',
  '',
  'Apply with:',
  '',
  '```bash',
  'terraform init',
  'terraform plan -out=tfplan',
  'terraform apply tfplan',
  '```',
  '',
  '\x1b[?2004hroot@aks-agent-mno345:/app# ',
].join('\n');
